apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-challenge.fullname" . }}-a
  labels:
{{ include "devops-challenge.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "devops-challenge.name" . }}-a
    app.kubernetes.io/instance: {{ .Release.Name }}
