# Default values for devops-challenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  acceleration_dv: acceleration-dv
  acceleration_a: acceleration-a
  acceleration_calc: acceleration-calc
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

probes:
  init: 5
  period: 3
  success: 1
  failure: 1
  timeout: 1

service:
  type: ClusterIP
  port: 80
  a:
    containerPort: 3002
  calc:
    containerPort: 3000
  dv:
    containerPort: 3001

ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: calc.devops-challenge

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
